
export const GET_MUSIC_RECORDS_LOADING = "GET_MUSIC_RECORDS_LOADING"
export const GET_MUSIC_RECORDS_SUCCESS = "GET_MUSIC_RECORDS_SUCCESS"
export const GET_MUSIC_RECORDS_FAILURE = "GET_MUSIC_RECORDS_FAILURE" 

export const EDIT_MUSIC_RECORDS_REQUEST = "EDIT_MUSIC_RECORDS_REQUEST"
export const EDIT_MUSIC_RECORDS_SUCCESS = "EDIT_MUSIC_RECORDS_SUCCESS"
export const EDIT_MUSIC_RECORDS_FAILURE = "EDIT_MUSIC_RECORDS_FAILURE"