
export const GET_MUSIC_RECORD = "GET_MUSIC_RECORD"
export const GET_MUSIC_RECORD_REQUEST = "GET_MUSIC_RECORD_REQUEST"
export const GET_MUSIC_RECORD_FAILURE = "GET_MUSIC_RECORD_FAILURE" 

export const EDIT_DATA_REQUEST = "EDIT_DATA_REQUEST"
export const EDIT_DATA_SUCCESS = "EDIT_DATA_SUCCESS"
export const EDIT_DATA_FAILURE = "EDIT_DATA_FAILURE"